# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: 273do
# "service" is the name of this project. This will also be added to your AWS resource names.
service: thor-web-app-be

custom:
  wsgi:
    app: app.app
    pythonBin: /usr/bin/python3

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
